#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../shared/lib/functions.sh"
source "$SCRIPT_DIR/../shared/lib/styles.sh"

usage() {
    gum style --foreground 212 --border normal --padding "0 1" \
        "Arguments are missing" "" \
        "Use: ${0##*/} <project_name>"

    add_to_do "logging is not configured"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

info "Configuring logging..."

PROJECT_NAME="$1"

cd "/var/www/$PROJECT_NAME"

if [ -f .env ]; then
    sed -i "s/^LOG_CHANNEL=.*/LOG_CHANNEL=daily/" .env
    sed -i "s/^LOG_LEVEL=.*/LOG_LEVEL=debug/" .env
    sed -i "/^LOG_DAILY_DAYS=/d" .env
    sed -i "/^LOG_LEVEL=.*/a LOG_DAILY_DAYS=7" .env
else
    add_to_do "Failed to configure logging : .env file not found"
    exit 1
fi

exit 0