#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../shared/lib/functions.sh"
source "$SCRIPT_DIR/../shared/lib/styles.sh"

# Standalone usage
usage() {
    gum style --foreground 212 --border normal --padding "0 1" \
        "Arguments are missing" "" \
        "Use: ${0##*/} <project_name>"
    exit 1
}

# Check arguments
if [ $# -ne 1 ]; then
    usage
fi

PROJECT_NAME="$1"

info "Configuring test environment..."

cd "/var/www/$PROJECT_NAME"

# copy app_key from .env file
CURRENT_APP_KEY=$(grep "APP_KEY=" .env | cut -d '=' -f2)

# create the .env.testing file
cat <<EOF > .env.testing
APP_ENV=testing

APP_KEY=

DB_CONNECTION=sqlite
DB_DATABASE=:memory:

CACHE_DRIVER=array
FILESYSTEM_DISK=local
SESSION_DRIVER=array
SESSION_LIFETIME=120

QUEUE_CONNECTION=sync
MAIL_MAILER=array

BCRYPT_ROUNDS=4
EOF

# copy .env.testing to .env.testing.example
cp .env.testing .env.testing.example

# add app_key to .env.testing
sed -i "s|^APP_KEY=.*|APP_KEY=$CURRENT_APP_KEY|" .env.testing

# check syntax in Pest.php
if [ -f "tests/Pest.php" ]; then
    if grep -q "// ->use(RefreshDatabase::class)" tests/Pest.php; then
        sed -i "s|// ->use(RefreshDatabase::class)|   ->use(RefreshDatabase::class)|" tests/Pest.php
    fi
else
    add_to_do "check for tests/Pest.php file as file was not found"
    exit 1
fi

php artisan config:clear
php artisan migrate --force --env=testing

exit 0