#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/../lib/styles.sh"
source "$SCRIPT_DIR/../lib/functions.sh"

# create temporary file
WEB_FILE="/var/www/html/sys_check.php"
echo "<?php echo PHP_VERSION;" | sudo tee $WEB_FILE > /dev/null

# get php versions
CLI_VER=$(php -r 'echo PHP_VERSION;' 2>/dev/null)
WEB_VER=$(curl -s --fail http://127.0.0.1/sys_check.php)

# remove temporary file
sudo rm $WEB_FILE

if [ -z "$WEB_VER" ]; then
    error "Cannot retrieve PHP version through apache2."
    exit 1
fi

echo "    CLI PHP: $CLI_VER"
echo "    Web PHP: $WEB_VER"

if [ "$CLI_VER" != "$WEB_VER" ]; then
    warning "WARNING: Web uses $WEB_VER and CLI uses $CLI_VER !"
else
    success "Web uses $WEB_VER and CLI uses $CLI_VER !"
fi

exit 0
