#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/styles.sh"

# Usage standalone
usage() {
    gum style --foreground 212 --border normal --padding "0 1" \
        "Arguments are missing" "" \
        "Use: ${0##*/} <DB_NAME> <DB_USER> <DB_PASSWORD>"
    exit 1
}

# Check arguments
[ $# -ne 3 ] && usage

DB_NAME=$1
DB_USER=$2
DB_PASSWORD=$3

info "Installing database and user..."

echo "    Creating Database '$DB_NAME'..."

if ! MYSQL_ERROR=$(sudo mysql -e "CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" > /dev/null 2>&1); then
    error "$MYSQL_ERROR"
    exit 1
fi

echo "    Creating user '$DB_USER'..."

if ! MYSQL_ERROR=$(sudo mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$DB_PASSWORD'; 
    GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'127.0.0.1';
    FLUSH PRIVILEGES;" > /dev/null 2>&1); then
    error "$MYSQL_ERROR"
    exit 1
fi

exit 0
